sudo: required
services:
    - docker

before_install:
    - docker build -t evgenii88/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true evgenii88/docker-react npm run test -- --coverage
